## Nornir Config File 
#---
#core:
#  num_workers: 10

#inventory:
#  plugin: "nornir.plugins.inventory.simple.SimpleInventory"

# options: 
#    host_file: "~/network-programmability/SCRIPTS/Nornir/inventory/hosts.yml"
#   group_file: "~/network-programmability/SCRIPTS/Nornir/inventory/groups.yml"
#   defaults_file: "~/network-programmability/SCRIPTS/Nornir/inventory/defaults.yml"

## Nornir 3.0 Config File 

inventory:
    plugin: SimpleInventory
    options: 
        host_file: "inventory/hosts.yml"
        group_file: "inventory/groups.yml"
        defaults_file: "inventory/defaults.yml"

runners: 
    plugin: threaded
    options: 
        num_workers: 20